<?php

namespace Cherrycake\ItemAdmin;

const FORM_ITEM_TYPE_NUMERIC = 0;
const FORM_ITEM_TYPE_STRING = 1;
const FORM_ITEM_TYPE_TEXT = 2;
const FORM_ITEM_TYPE_BOOLEAN = 3;
const FORM_ITEM_TYPE_RADIOS = 4;
const FORM_ITEM_TYPE_SELECT = 5;
const FORM_ITEM_TYPE_DATABASE_QUERY = 6;
const FORM_ITEM_TYPE_COUNTRY = 7;

const FORM_ITEM_META_TYPE_MULTILEVEL_SELECT = 0;
const FORM_ITEM_META_TYPE_LOCATION = 1;
