<?php

namespace Cherrycake\Login;

const LOGIN_PASSWORD_ENCRYPTION_METHOD_PBKDF2 = 0;

const LOGIN_RESULT_OK = 0;
const LOGIN_RESULT_FAILED = 1;
const LOGIN_RESULT_FAILED_UNKNOWN_USER = 2;
const LOGIN_RESULT_FAILED_WRONG_PASSWORD = 3;

const LOGOUT_RESULT_OK = 0;
const LOGOUT_RESULT_FAILED = 1;
