<?php

namespace Cherrycake\Database;

const DATABASE_FIELD_TYPE_INTEGER = 0;
const DATABASE_FIELD_TYPE_TINYINT = 1;
const DATABASE_FIELD_TYPE_FLOAT = 2;
const DATABASE_FIELD_TYPE_DATE = 3;
const DATABASE_FIELD_TYPE_DATETIME = 4;
const DATABASE_FIELD_TYPE_TIMESTAMP = 5;
const DATABASE_FIELD_TYPE_TIME = 6;
const DATABASE_FIELD_TYPE_YEAR = 7;
const DATABASE_FIELD_TYPE_STRING = 8;
const DATABASE_FIELD_TYPE_TEXT = 9;
const DATABASE_FIELD_TYPE_BLOB = 10;
const DATABASE_FIELD_TYPE_BOOLEAN = 11;
const DATABASE_FIELD_TYPE_IP = 12;
const DATABASE_FIELD_TYPE_SERIALIZED = 13;
const DATABASE_FIELD_TYPE_COLOR = 14;

const DATABASE_FIELD_DEFAULT_VALUE = 0;
const DATABASE_FIELD_DEFAULT_VALUE_DATE = 1;
const DATABASE_FIELD_DEFAULT_VALUE_DATETIME = 2;
const DATABASE_FIELD_DEFAULT_VALUE_TIMESTAMP = 3;
const DATABASE_FIELD_DEFAULT_VALUE_TIME = 4;
const DATABASE_FIELD_DEFAULT_VALUE_YEAR = 5;
const DATABASE_FIELD_DEFAULT_VALUE_IP = 6;
const DATABASE_FIELD_DEFAULT_VALUE_AVAILABLE_URL_SHORT_CODE = 7;
