<?php

namespace Cherrycake\Stats;

const STATS_EVENT_TIME_RESOLUTION_MINUTE = 0;
const STATS_EVENT_TIME_RESOLUTION_HOUR = 1;
const STATS_EVENT_TIME_RESOLUTION_DAY = 2;
const STATS_EVENT_TIME_RESOLUTION_MONTH = 3;
const STATS_EVENT_TIME_RESOLUTION_YEAR = 4;
